"""
Failure Demo Script — P2P Churn Resilience

Demonstrates the impact of killing high-degree nodes on search coverage.
Compares metrics before and after failure.

Usage:
    python failure_demo.py

Requires:
    - topology.json (generated by bootstrap.py)
    - All 100 peers running (via run_all.sh or manually)
"""

import asyncio
import json
import os
import random
import time

from query import (
    ALL_PORTS, send_query, reset_all_peers,
    collect_all_metrics, send_message
)

BLOCKED_PEERS = set()  # No blocked peers with port range 6000-6099
K = 5  # Number of high-degree nodes to kill


def load_topology(path="topology.json"):
    return json.load(open(path))


def build_adjacency(topology):
    n = len(topology["peers"])
    adj = {i: [] for i in range(n)}
    for a, b in topology["edges"]:
        adj[a].append(b)
        adj[b].append(a)
    return adj


def get_file_pool(topology):
    return list(set(f for files in topology["files"].values() for f in files))


def count_peers_with_file(topology, keyword):
    return sum(
        1 for files in topology["files"].values() if keyword in files
    )


async def run_query(label, source_port, keyword, ttl=5):
    """Run a single query and collect extended metrics."""
    await reset_all_peers()
    metrics = await send_query(source_port, keyword, ttl)

    total_with_file = count_peers_with_file(load_topology(), keyword)
    coverage_ratio = metrics["matched_peers_count"] / max(total_with_file, 1)
    dup_ratio = (
        metrics["duplicate_queries_dropped"]
        / max(metrics["messages_sent"], 1)
    )

    hops = metrics.get("hops", [])
    avg_hops = sum(hops) / len(hops) if hops else 0.0
    lats = metrics.get("latencies", [])
    avg_lat = sum(lats) / len(lats) if lats else 0.0

    print(f"  [{label}]")
    print(f"    matched_peers_count:       {metrics['matched_peers_count']}")
    print(f"    total_peers_having_file:   {total_with_file}")
    print(f"    coverage_ratio:            {coverage_ratio:.2f}")
    print(f"    messages_sent:             {metrics['messages_sent']}")
    print(f"    duplicate_queries_dropped: {metrics['duplicate_queries_dropped']}")
    print(f"    duplicate_ratio:           {dup_ratio:.3f}")
    print(f"    avg_hops:                  {avg_hops:.2f}")
    print(f"    avg_latency_ms:            {avg_lat:.1f}")
    print(f"    failed_forward_count:      {metrics['failed_forward_count']}")
    print(f"    dead_neighbors_detected:   {metrics['dead_neighbors_detected']}")

    return {
        "matched_peers_count": metrics["matched_peers_count"],
        "total_peers_having_file": total_with_file,
        "coverage_ratio": coverage_ratio,
        "messages_sent": metrics["messages_sent"],
        "duplicate_ratio": dup_ratio,
        "avg_hops": avg_hops,
        "avg_latency_ms": avg_lat,
        "failed_forward_count": metrics["failed_forward_count"],
        "dead_neighbors_detected": metrics["dead_neighbors_detected"],
    }


async def main():
    topology = load_topology()
    adj = build_adjacency(topology)
    pool = get_file_pool(topology)

    # Find high-degree nodes
    degrees = sorted(
        range(100), key=lambda i: len(adj[i]), reverse=True
    )
    high_degree_ids = [d for d in degrees if d not in BLOCKED_PEERS][:K]

    # Pick a source that is NOT a high-degree node
    source_id = next(
        i for i in range(100)
        if i not in high_degree_ids and i not in BLOCKED_PEERS
    )
    source_port = topology["peers"][source_id]["port"]
    keyword = random.choice(pool)

    print("=" * 60)
    print("P2P FAILURE DEMO — Churn Resilience Test")
    print("=" * 60)
    print(f"\nTopology: 100 peers")
    print(f"High-degree nodes to kill: {high_degree_ids}")
    print(f"Source peer:               {source_id} (port {source_port})")
    print(f"Keyword:                   '{keyword}'")

    # ---- Before failure ----
    print(f"\n--- Phase 1: Before failure ---")
    before = await run_query("BEFORE", source_port, keyword)

    # ---- Kill high-degree nodes ----
    print(f"\n--- Phase 2: Killing {K} high-degree nodes ---")
    for node_id in high_degree_ids:
        print(f"  Sending SHUTDOWN to Peer {node_id}...")
        await send_message(topology["peers"][node_id]["port"], {"type": "SHUTDOWN"})
    print(f"  Waiting for heartbeat to detect failures...")
    await asyncio.sleep(6)  # Wait for at least one heartbeat cycle

    # ---- After failure ----
    print(f"\n--- Phase 3: After failure ---")
    after = await run_query("AFTER", source_port, keyword)

    # ---- Summary ----
    print(f"\n" + "=" * 60)
    print("FAILURE DEMO SUMMARY")
    print("=" * 60)
    print(f"{'Metric':<30} {'Before':>10} {'After':>10} {'Change':>10}")
    print("-" * 60)
    print(
        f"{'matched_peers_count':<30} {before['matched_peers_count']:>10} "
        f"{after['matched_peers_count']:>10} "
        f"{after['matched_peers_count'] - before['matched_peers_count']:>+10}"
    )
    print(
        f"{'coverage_ratio':<30} {before['coverage_ratio']:.2f}{'':>8} "
        f"{after['coverage_ratio']:.2f}{'':>8} "
        f"{after['coverage_ratio'] - before['coverage_ratio']:+.2f}{'':>8}"
    )
    print(
        f"{'messages_sent':<30} {before['messages_sent']:>10} "
        f"{after['messages_sent']:>10} "
        f"{after['messages_sent'] - before['messages_sent']:>+10}"
    )
    print(
        f"{'duplicate_ratio':<30} {before['duplicate_ratio']:.3f}{'':>8} "
        f"{after['duplicate_ratio']:.3f}{'':>8} "
        f"{after['duplicate_ratio'] - before['duplicate_ratio']:+.3f}{'':>8}"
    )
    print(
        f"{'avg_hops':<30} {before['avg_hops']:.2f}{'':>9} "
        f"{after['avg_hops']:.2f}{'':>9} "
        f"{after['avg_hops'] - before['avg_hops']:+.2f}{'':>9}"
    )
    print(
        f"{'avg_latency_ms':<30} {before['avg_latency_ms']:.1f}{'':>8} "
        f"{after['avg_latency_ms']:.1f}{'':>8} "
        f"{after['avg_latency_ms'] - before['avg_latency_ms']:+.1f}{'':>8}"
    )
    print(
        f"{'failed_forward_count':<30} {before['failed_forward_count']:>10} "
        f"{after['failed_forward_count']:>10} "
        f"{after['failed_forward_count'] - before['failed_forward_count']:>+10}"
    )
    print(
        f"{'dead_neighbors_detected':<30} {before['dead_neighbors_detected']:>10} "
        f"{after['dead_neighbors_detected']:>10} "
        f"{after['dead_neighbors_detected'] - before['dead_neighbors_detected']:>+10}"
    )
    print("-" * 60)

    # ---- Save report ----
    os.makedirs("results", exist_ok=True)
    with open("results/failure_report.txt", "w") as f:
        f.write("Failure Demo Report\n")
        f.write("-" * 50 + "\n")
        f.write(f"Killed nodes: {high_degree_ids}\n")
        f.write(f"Source peer:  {source_id}\n")
        f.write(f"Keyword:      '{keyword}'\n")
        f.write(f"TTL:          5\n\n")
        f.write(f"{'Metric':<30} {'Before':>10} {'After':>10}\n")
        f.write("-" * 50 + "\n")
        for key in ["matched_peers_count", "coverage_ratio", "messages_sent",
                     "duplicate_ratio", "avg_hops", "avg_latency_ms",
                     "failed_forward_count", "dead_neighbors_detected"]:
            b = before[key]
            a = after[key]
            if isinstance(b, float):
                f.write(f"{key:<30} {b:>10.3f} {a:>10.3f}\n")
            else:
                f.write(f"{key:<30} {b:>10} {a:>10}\n")
        f.write("\nExplanation:\n")
        f.write(
            "After high-degree nodes leave, the overlay loses important "
            "routing paths.\n"
            "Peers detect failed neighbors via heartbeat and stop forwarding "
            "messages to them.\n"
            "Search still works if the remaining overlay is connected, "
            "but coverage may decrease.\n"
        )
    print(f"\nSaved: results/failure_report.txt")

    # ---- Generate chart if matplotlib is available ----
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt

        labels = ['Before\n(0 killed)', f'After\n({K} killed)']
        values = [before['matched_peers_count'], after['matched_peers_count']]
        covs = [before['coverage_ratio'], after['coverage_ratio']]

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

        # Matched peers
        bars1 = ax1.bar(labels, values, color=['#4CAF50', '#F44336'], width=0.5)
        for bar, v in zip(bars1, values):
            ax1.text(bar.get_x() + bar.get_width() / 2,
                     bar.get_height() + 0.3, str(v),
                     ha='center', fontsize=12, fontweight='bold')
        ax1.set_ylabel("Matched Peers Count", fontsize=12)
        ax1.set_title("Search Coverage Before/After Failure", fontsize=13)
        ax1.grid(True, alpha=0.3, axis='y')

        # Coverage ratio
        bars2 = ax2.bar(labels, covs, color=['#4CAF50', '#F44336'], width=0.5)
        for bar, v in zip(bars2, covs):
            ax2.text(bar.get_x() + bar.get_width() / 2,
                     bar.get_height() + 0.005, f"{v:.2f}",
                     ha='center', fontsize=12, fontweight='bold')
        ax2.set_ylabel("Coverage Ratio", fontsize=12)
        ax2.set_title("Coverage Ratio Before/After Failure", fontsize=13)
        ax2.grid(True, alpha=0.3, axis='y')

        plt.suptitle(
            f"Failure Demo: {K} High-Degree Nodes Killed\n"
            f"(Nodes {high_degree_ids})",
            fontsize=14
        )
        plt.tight_layout()
        plt.savefig("results/failure_before_after.png", dpi=150)
        plt.close()
        print("Saved: results/failure_before_after.png (chart)")
    except ImportError:
        print("[failure_demo.py] matplotlib not installed — chart skipped")

    print("\nDone.")


if __name__ == "__main__":
    asyncio.run(main())
